import type { GolfCourse, GolfHole, GolfScorecard, GolfTee } from './scorecard';

function hole(partial: Partial<GolfHole> & { number: number; par: number | null }): GolfHole {
  return {
    number: partial.number,
    par: partial.par,
    yardage: partial.yardage ?? null,
    handicap: partial.handicap ?? null,
    strokes: partial.strokes ?? null,
    putts: partial.putts ?? null,
    fairway: partial.fairway ?? null,
    green: partial.green ?? null,
    score_to_par: partial.score_to_par ?? null,
  };
}

const PRESIDIO_COURSE: GolfCourse = {
  id: 'presidio-golf-course',
  name: 'Presidio Golf Course',
  city: 'San Francisco',
  state: 'CA',
};

const PRESIDIO_TEE: GolfTee = {
  name: 'Blue',
  gender: null,
  course_rating: 71.9,
  slope: 133,
  yardage: 6481,
};

/** Back nine only (holes 10-18), holes 10-14 recorded, 15-18 not yet played. */
export const NINE_HOLES_FROM_TEN: GolfScorecard = {
  version: 1,
  status: 'in_progress',
  course: PRESIDIO_COURSE,
  tee: PRESIDIO_TEE,
  holes_played: 9,
  starting_hole: 10,
  holes: [
    hole({
      number: 10,
      par: 4,
      yardage: 380,
      handicap: 7,
      strokes: 4,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 11,
      par: 5,
      yardage: 520,
      handicap: 1,
      strokes: 4,
      putts: 1,
      fairway: 'hit',
      green: 'hit',
      score_to_par: -1,
    }),
    hole({
      number: 12,
      par: 3,
      yardage: 165,
      handicap: 15,
      strokes: 3,
      putts: 2,
      fairway: null,
      green: 'short',
      score_to_par: 0,
    }),
    hole({
      number: 13,
      par: 4,
      yardage: 410,
      handicap: 3,
      strokes: 5,
      putts: 2,
      fairway: 'left',
      green: 'hit',
      score_to_par: 1,
    }),
    hole({
      number: 14,
      par: 4,
      yardage: 395,
      handicap: 9,
      strokes: 4,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({ number: 15, par: 4, yardage: 400, handicap: 5 }),
    hole({ number: 16, par: 3, yardage: 175, handicap: 17 }),
    hole({ number: 17, par: 5, yardage: 545, handicap: 11 }),
    hole({ number: 18, par: 4, yardage: 420, handicap: 13 }),
  ],
  summary: {
    holes_completed: 5,
    total_strokes: 20,
    total_par: 20,
    score_to_par: 0,
    total_putts: 9,
    fairways_hit: 3,
    fairways_possible: 4,
    greens_hit: 4,
    greens_possible: 5,
    fairway_misses: { left: 1, right: 0, short: 0, long: 0 },
    green_misses: { left: 0, right: 0, short: 1, long: 0 },
    front_nine: null,
    back_nine: { strokes: 20, par: 36, putts: 9 },
  },
};

/** Full 18, front nine complete, back nine just started (holes 10-11 recorded). */
export const EIGHTEEN_HOLES_MIXED: GolfScorecard = {
  version: 1,
  status: 'in_progress',
  course: PRESIDIO_COURSE,
  tee: PRESIDIO_TEE,
  holes_played: 18,
  starting_hole: 1,
  holes: [
    hole({
      number: 1,
      par: 4,
      yardage: 380,
      handicap: 7,
      strokes: 3,
      putts: 1,
      fairway: 'hit',
      green: 'hit',
      score_to_par: -1,
    }),
    hole({
      number: 2,
      par: 4,
      yardage: 410,
      handicap: 3,
      strokes: 4,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 3,
      par: 3,
      yardage: 165,
      handicap: 17,
      strokes: 3,
      putts: 1,
      fairway: null,
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 4,
      par: 5,
      yardage: 520,
      handicap: 1,
      strokes: 3,
      putts: 1,
      fairway: 'hit',
      green: 'hit',
      score_to_par: -2,
    }),
    hole({
      number: 5,
      par: 4,
      yardage: 395,
      handicap: 9,
      strokes: 5,
      putts: 2,
      fairway: 'right',
      green: 'hit',
      score_to_par: 1,
    }),
    hole({
      number: 6,
      par: 4,
      yardage: 375,
      handicap: 11,
      strokes: 6,
      putts: 2,
      fairway: 'hit',
      green: 'long',
      score_to_par: 2,
    }),
    hole({
      number: 7,
      par: 3,
      yardage: 178,
      handicap: 15,
      strokes: 5,
      putts: 2,
      fairway: null,
      green: 'short',
      score_to_par: 2,
    }),
    hole({
      number: 8,
      par: 5,
      yardage: 535,
      handicap: 5,
      strokes: 8,
      putts: 3,
      fairway: 'left',
      green: 'long',
      score_to_par: 3,
    }),
    hole({
      number: 9,
      par: 4,
      yardage: 400,
      handicap: 13,
      strokes: 4,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 10,
      par: 4,
      yardage: 385,
      handicap: 8,
      strokes: 5,
      putts: 2,
      fairway: 'hit',
      green: 'right',
      score_to_par: 1,
    }),
    hole({
      number: 11,
      par: 3,
      yardage: 172,
      handicap: 16,
      strokes: 3,
      putts: 1,
      fairway: null,
      green: 'hit',
      score_to_par: 0,
    }),
    hole({ number: 12, par: 5, yardage: 525, handicap: 2 }),
    hole({ number: 13, par: 4, yardage: 400, handicap: 10 }),
    hole({ number: 14, par: 4, yardage: 390, handicap: 12 }),
    hole({ number: 15, par: 3, yardage: 180, handicap: 18 }),
    hole({ number: 16, par: 5, yardage: 540, handicap: 6 }),
    hole({ number: 17, par: 4, yardage: 410, handicap: 4 }),
    hole({ number: 18, par: 4, yardage: 420, handicap: 14 }),
  ],
  summary: {
    holes_completed: 11,
    total_strokes: 49,
    total_par: 43,
    score_to_par: 6,
    total_putts: 19,
    fairways_hit: 6,
    fairways_possible: 8,
    greens_hit: 7,
    greens_possible: 11,
    fairway_misses: { left: 1, right: 1, short: 0, long: 0 },
    green_misses: { left: 0, right: 1, short: 1, long: 2 },
    front_nine: { strokes: 41, par: 36, putts: 16 },
    back_nine: { strokes: 8, par: 36, putts: 3 },
  },
};

/** Same round as EIGHTEEN_HOLES_MIXED, played out to completion. */
export const EIGHTEEN_HOLES_COMPLETE: GolfScorecard = {
  version: 1,
  status: 'complete',
  course: PRESIDIO_COURSE,
  tee: PRESIDIO_TEE,
  holes_played: 18,
  starting_hole: 1,
  holes: [
    ...EIGHTEEN_HOLES_MIXED.holes.slice(0, 11),
    hole({
      number: 12,
      par: 5,
      yardage: 525,
      handicap: 2,
      strokes: 5,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 13,
      par: 4,
      yardage: 400,
      handicap: 10,
      strokes: 4,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 14,
      par: 4,
      yardage: 390,
      handicap: 12,
      strokes: 4,
      putts: 1,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 15,
      par: 3,
      yardage: 180,
      handicap: 18,
      strokes: 4,
      putts: 2,
      fairway: null,
      green: 'short',
      score_to_par: 1,
    }),
    hole({
      number: 16,
      par: 5,
      yardage: 540,
      handicap: 6,
      strokes: 6,
      putts: 2,
      fairway: 'right',
      green: 'hit',
      score_to_par: 1,
    }),
    hole({
      number: 17,
      par: 4,
      yardage: 410,
      handicap: 4,
      strokes: 4,
      putts: 2,
      fairway: 'hit',
      green: 'hit',
      score_to_par: 0,
    }),
    hole({
      number: 18,
      par: 4,
      yardage: 420,
      handicap: 14,
      strokes: 5,
      putts: 2,
      fairway: 'hit',
      green: 'long',
      score_to_par: 1,
    }),
  ],
  summary: {
    holes_completed: 18,
    total_strokes: 81,
    total_par: 72,
    score_to_par: 9,
    total_putts: 32,
    fairways_hit: 11,
    fairways_possible: 14,
    greens_hit: 12,
    greens_possible: 18,
    fairway_misses: { left: 1, right: 2, short: 0, long: 0 },
    green_misses: { left: 0, right: 1, short: 2, long: 3 },
    front_nine: { strokes: 41, par: 36, putts: 16 },
    back_nine: { strokes: 40, par: 36, putts: 16 },
  },
};

export const SETUP_EMPTY: GolfScorecard = {
  version: 1,
  status: 'setup',
  course: null,
  tee: null,
  holes_played: null,
  starting_hole: null,
  holes: [],
  summary: null,
};
